// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZk0y-Z5VBp1eZjYAYZhAyRUmJrpi03cc',
    appId: '1:1013318087083:web:67be6f3d866c9a254962ee',
    messagingSenderId: '1013318087083',
    projectId: 'financialcalculator-772f1',
    authDomain: 'financialcalculator-772f1.firebaseapp.com',
    storageBucket: 'financialcalculator-772f1.firebasestorage.app',
    measurementId: 'G-7MRC56LZ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrV-CLlsqHcmMq-qNIuffyNx1Rbtaqk4',
    appId: '1:1013318087083:android:79dabb4bae7aca244962ee',
    messagingSenderId: '1013318087083',
    projectId: 'financialcalculator-772f1',
    storageBucket: 'financialcalculator-772f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6ho59lPJ1kZKkx6EDVrHGr6yauoCb90',
    appId: '1:1013318087083:ios:add105af1615b36a4962ee',
    messagingSenderId: '1013318087083',
    projectId: 'financialcalculator-772f1',
    storageBucket: 'financialcalculator-772f1.firebasestorage.app',
    iosBundleId: 'com.example.financialCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6ho59lPJ1kZKkx6EDVrHGr6yauoCb90',
    appId: '1:1013318087083:ios:add105af1615b36a4962ee',
    messagingSenderId: '1013318087083',
    projectId: 'financialcalculator-772f1',
    storageBucket: 'financialcalculator-772f1.firebasestorage.app',
    iosBundleId: 'com.example.financialCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZk0y-Z5VBp1eZjYAYZhAyRUmJrpi03cc',
    appId: '1:1013318087083:web:583992cf656fc37b4962ee',
    messagingSenderId: '1013318087083',
    projectId: 'financialcalculator-772f1',
    authDomain: 'financialcalculator-772f1.firebaseapp.com',
    storageBucket: 'financialcalculator-772f1.firebasestorage.app',
    measurementId: 'G-GK64JVPX0R',
  );
}
